# Generated by Django 2.0.4 on 2018-04-05 13:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='geo coords of the parking spot', srid=4326)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpotReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('start_ts', models.DateTimeField(verbose_name='reservation start date')),
                ('end_ts', models.DateTimeField(verbose_name='reservation end date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('parkingspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.ParkingSpot')),
            ],
        ),
    ]
