# Generated by Django 2.0.4 on 2018-04-04 23:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='geo coords of the parking spot', srid=4326)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reservation_date', models.DateTimeField(verbose_name='reservation date')),
                ('create_date', models.DateTimeField(verbose_name='creation date')),
                ('parkingspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpot')),
            ],
        ),
    ]
