# Generated by Django 2.0.4 on 2018-04-04 22:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='geo coords of the parking spot', srid=4326)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
